Use /clusters/:id/upgrades resource
Mirantis/Kostyor-cli pull request #8
Opened 2016-09-22 12:54 UTC by ikalnitsky

Since PR #39 [1] to Kostyor, there's a new RESTful upgrade resource
available at URI:

    /clusters/:id/upgrades

Thus, we need to provide a commands to interact with it. This commit
adds the following commands:

    $ kostyor upgrade-list <cluster>
    $ kostyor upgrade-show <upgrade>
    $ kostyor upgrade-start <cluster>
    $ kostyor upgrade-pause <cluster>
    $ kostyor upgrade-continue <cluster>
    $ kostyor upgrade-cancel <cluster>
    $ kostyor upgrade-rollback <cluster>

TODO: We need to consider to pass <cluster> instead of <upgrade> to
      upgrade-show command in order to be consistent with rest of the
      commands.

The commit also fixes #6 by providing detailed information about upgrade
tasks.

[1] https://github.com/sc68cal/Kostyor/pull/39

2016-09-26 13:55 UTC, jvarlamova reviewed
Looks good to me.

2016-09-26 16:56 UTC, sc68cal commented on kostyor_cli/main.py
> +        self.baseurl = 'http://{0}:{1}'.format(host, port)
This is a change that is:

* Not discussed in the commit message
* Is a significant change

I would prefer that this be broken up into a separate commit

2016-09-26 16:57 UTC, sc68cal requested changes

2016-09-26 16:59 UTC, ikalnitsky commented on kostyor_cli/main.py
> +        self.baseurl = 'http://{0}:{1}'.format(host, port)
You mean `baseurl` or `requests.Session()`?

2016-09-26 17:01 UTC, sc68cal commented on kostyor_cli/main.py
> +        self.baseurl = 'http://{0}:{1}'.format(host, port)
This whole chunk of code. It's good that you're introducing it, but it should really be its own commit

2016-09-26 17:06 UTC, ikalnitsky commented on kostyor_cli/main.py
> +        self.baseurl = 'http://{0}:{1}'.format(host, port)
Agree. Do you ok with it generally?

2016-09-26 17:16 UTC, sc68cal commented on kostyor_cli/main.py
> +        self.baseurl = 'http://{0}:{1}'.format(host, port)
yeah I think the change is very good, I just want to see it as a separate commit

2016-09-26 17:17 UTC, sc68cal commented on kostyor_cli/main.py
> +        self.baseurl = 'http://{0}:{1}'.format(host, port)
It can still be part of this pull request, I just want you to break it out into its own commit

2016-09-27 07:42 UTC, ikalnitsky commented on kostyor_cli/main.py
> +        self.baseurl = 'http://{0}:{1}'.format(host, port)
yeah, i got it. i totally agree. i'll fix it.

2016-09-27 18:08 UTC, sc68cal approved these changes

2016-09-27 18:09 UTC, merged